//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RmitJourneyPlanner.CoreLibraries.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RmitJourneyPlanner.CoreLibraries.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Gets the SQL query to initilize an arc cache.
        /// </summary>
        internal static string rmitjourneyplanner_arccache {
            get {
                return ResourceManager.GetString("rmitjourneyplanner_arccache", resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the SQL query to initilize a location cache.
        /// </summary>
        internal static string rmitjourneyplanner_locationcache {
            get {
                return ResourceManager.GetString("rmitjourneyplanner_locationcache", resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the SQL query to initilize a node cache.
        /// </summary>
        internal static string rmitjourneyplanner_nodecache {
            get {
                return ResourceManager.GetString("rmitjourneyplanner_nodecache", resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the SQL query to initilize a node/route cache.
        /// </summary>
        internal static string rmitjourneyplanner_noderoutecache {
            get {
                return ResourceManager.GetString("rmitjourneyplanner_noderoutecache", resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the SQL query to initilize an route cache.
        /// </summary>
        internal static string rmitjourneyplanner_routecache {
            get {
                return ResourceManager.GetString("rmitjourneyplanner_routecache", resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the SQL query to initilize a schedule collection cache.
        /// </summary>
        internal static string rmitjourneyplanner_schedulecollectioncache {
            get {
                return ResourceManager.GetString("rmitjourneyplanner_schedulecollectioncache", resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the SQL query to initilize a trip/schedule cache.
        /// </summary>
        internal static string rmitjourneyplanner_tripschedulecache {
            get {
                return ResourceManager.GetString("rmitjourneyplanner_tripschedulecache", resourceCulture);
            }
        }
    }
}
