// -----------------------------------------------------------------------
// <copyright file="TramTrackerAPI.cs" company="">
// TODO: Update copyright text.
// </copyright>
// -----------------------------------------------------------------------

namespace RmitJourneyPlanner.CoreLibraries.DataAccess
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Text.RegularExpressions;
    using System.Xml;

    /// <summary>
    /// Interfaces with the Yarra Trams Tramtracker SOAP webservice to get various data.
    /// </summary>
    public class TramTrackerAPI : XMLRequester
    {
        /// <summary>
        /// The regular expression that defines the correct format of a client UUID.
        /// </summary>
        private const string uuidFormat = "[a-zA-Z0-9]{8}-[a-zA-Z0-9]{4}-[a-zA-Z0-9]{4}-[a-zA-Z0-9]{4}-[a-zA-Z0-9]{12}";
        
        private string guid;
        private string clientType = "RMIT Travel Planner";
        private string clientVersion = "0.0.0.1";
        private string clientWebServiceVersion = "6.4.0.0";
        private string osVersion = Environment.OSVersion.VersionString;

        /// <summary>
        /// Initializes a new instance of the TramTrackerAPI class.
        /// </summary>
        public TramTrackerAPI() : base (Urls.TramTrackerUrl)
        {
            this.guid = getNewGuid();
            this.HeaderParameters["PidsClientHeader"] = generateHeader();
        }

        /// <summary>
        /// Requests the Tramtracker webservice for a new client UUID.
        /// </summary>
        /// <returns></returns>
        private string getNewGuid()
        {
            //Set parameters
            base.RequestType = RequestType.SOAP;
            base.SoapXmlNamespace = Urls.TramTrackerUrl;
            base.SoapAction = Urls.GetNewClientGuid;
            base.Parameters["GetNewClientGuid"] = null;
            //Request data
            XmlDocument doc = base.Request();
            
            //Get response data
            XmlNode response = doc["soap:Envelope"]["soap:Body"]["GetNewClientGuidResponse"];
            return response["GetNewClientGuidResult"].InnerText;
        }

        /// <summary>
        /// Gets the client GUID generated by the TramTracker webservice.
        /// </summary>
        public string Guid
        {
            get
            {
                return guid;
            }
        }

        /// <summary>
        /// Gets or sets the client type reported to the Tramtracker webservice.
        /// </summary>
        public string ClientType
        {
            get
            {
                return clientType;
            }
            set
            {
                clientType = value;
            }
        }

        /// <summary>
        /// Gets or sets the client version reported to the Tramtracker webservice.
        /// </summary>
        public string ClientVersion
        {
            get
            {
                return clientVersion;
            }
            set
            {
                clientVersion = value;
            }
        }

        /// <summary>
        /// Gets or sets the web service version reported to the Tramtracker webservice. 
        /// This shouldn't need to be changed off the default.
        /// </summary>
        public string ClientWebServiceVersion
        {
            get
            {
                return clientWebServiceVersion;
            }
            set
            {
                clientWebServiceVersion = value;
            }
        }

        /// <summary>
        /// Gets or sets the operating system version that is reported to the Tramtracker webservice.
        /// This is usually autodetected and doesn't need to be changed off the default.
        /// </summary>
        public string ClientOSVersion
        {
            get
            {
                return osVersion;
            }
            set
            {
                osVersion = value;
            }

        }

        /// <summary>
        /// Generate the required header for the Tramtracker webservice.
        /// </summary>
        /// <returns></returns>
        private XmlNode generateHeader()
        {

            /*
              Header Template:
             * <PidsClientHeader xmlns="http://www.yarratrams.com.au/pidsservice/">
                <ClientGuid>guid</ClientGuid>
                <ClientType>string</ClientType>
                <ClientVersion>string</ClientVersion>
                <ClientWebServiceVersion>string</ClientWebServiceVersion>
                <OSVersion>string</OSVersion>
                </PidsClientHeader>
             */
            XmlDocument doc = new XmlDocument();

            XmlNode nClientHeader = doc.CreateElement("PidsClientHeader", base.SoapXmlNamespace);
            
            XmlNode nClientGuid = doc.CreateElement("ClientGuid");
            XmlNode nClientType = doc.CreateElement("ClientType");
            XmlNode nClientVersion = doc.CreateElement("ClientVersion");
            XmlNode nClientWebServiceVersion =doc.CreateElement("ClientWebServiceVersion");
            XmlNode nOsVersion = doc.CreateElement("OSVersion");
            
            nClientGuid.InnerText= guid;
            nClientType.InnerText = clientType;
            nClientVersion.InnerText = clientVersion;
            nClientWebServiceVersion.InnerText = clientWebServiceVersion;
            nOsVersion.InnerText = osVersion;

            doc.AppendChild(nClientHeader);
            nClientHeader.AppendChild(nClientGuid);
            nClientHeader.AppendChild(nClientType);
            nClientHeader.AppendChild(nClientVersion);
            nClientHeader.AppendChild(nClientWebServiceVersion);
            nClientHeader.AppendChild(nOsVersion);

            return nClientHeader;
        }

        /// <summary>
        /// Returns true if the supplied string is in the correct format for a client UUID.
        /// </summary>
        /// <param name="uuid"></param>
        /// <returns></returns>
        public bool IsValidUuid(string uuid)
        {            
            return new Regex(uuidFormat).IsMatch(uuid);
        }

    }
}
