// -----------------------------------------------------------------------
// <copyright file="TramTrackerAPI.cs" company="">
// TODO: Update copyright text.
// </copyright>
// -----------------------------------------------------------------------

namespace RmitJourneyPlanner.CoreLibraries.DataAccess
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Xml;

    /// <summary>
    /// Interfaces with the Yarra Trams Tramtracker SOAP webservice to get various data.
    /// </summary>
    public class TramTrackerAPI : XMLRequester
    {
        private string guid;

        public TramTrackerAPI() : base (Urls.TramTrackerUrl)
        {
            this.guid = getNewGuid();

               
        }

        private string getNewGuid()
        {
            //Set parameters
            base.RequestType = RequestType.SOAP;
            base.SoapXmlNamespace = Urls.TramTrackerUrl;
            base.SoapAction = Urls.GetNewClientGuid;
            base.Parameters["GetNewClientGuid"] = null;
            //Request data
            XmlDocument doc = base.Request();
            
            //Get response data
            XmlNode response = doc["soap:Envelope"]["soap:Body"]["GetNewClientGuidResponse"];
            return response["GetNewClientGuidResult"].InnerText;
        }

        /// <summary>
        /// Gets the client GUID generated by the TramTracker API.
        /// </summary>
        public string Guid
        {
            get
            {
                return guid;
            }
        }

    }
}
